name: Maven CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'


      - name: Build and Install with Maven
        run: mvn clean install -B --file pom.xml

      - name: Run TestNG Suite
        run: mvn test -DsuiteXmlFile=testNg.xml -Dmaven.test.failure.ignore=true

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: Report/DouglastestAutomation/