name: Maven CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 23 (using actions/setup-java@v2)
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23.0.2'  # Make sure JDK 23 is available; you can also use the latest supported version


      - name: Build and Install with Maven
        run: mvn clean install -B --file pom.xml

      - name: Run TestNG Suite
        run: mvn test -DsuiteXmlFile=testNg.xml

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: Report/DouglastestAutomation/